### ISSUE TITLE
Reorder output folder structure

### ISSUE THREAD

**Issue by daisymut** [nf-core/sammyseq#13]
- now .bam are in ${outdir}/bwa and .bam.bai are in ${outdir}/samtools 
```[tasklist]
### Tasks
- [x] genome/ containing bwa index (if created in the run with --save-reference) and genome.sizes
- [x] (optional) alignment/bwa/ containing bam and associated bai files
- [x] alignment/markduplicates/ containing dup marked bam and associated bai files
- [x] single_tracks/deeptiools/ containing bigwig .bw files
- [x] (optional) comparisons/spp_mle/ containing pairwise bigwig .bw files
```
